### ISSUE TITLE
Assistant works but once in the MagicMirror, it won't take my Ok Google

### ISSUE THREAD

**Issue by godinperson** [gauravsacc/MMM-GoogleAssistant#11]
Hi,

 I've installed your module, the assistant works fine but once I launch the MagicMirror, it won't work.

How to test?

Thanks

**Comment by gauravsacc** [comment]
You need to have both assistant and MagicMirror running in parallel

**Comment by godinperson** [comment]
How do I make it run at the same time? Did I miss steps? Also, what is the difference between MMM-Assistant and MMM-GoogleAssistant?

Thanks

**Comment by gauravsacc** [comment]
run assistant.py and MagicMirror in two different terminal windows. 
I wrote this as a quick proof of concept 3 months back and since then haven't had anytime update this and build features listed in the What's coming section in Readme.md

MMM-Assistant is from another developer who is building a similar module along the same ideas. Here's the discussion https://forum.magicmirror.builders/topic/4936/need-help-for-testing-modules

**Comment by godinperson** [comment]
Great, I made it work. Would like to know how to automate it or make it run inside the MagicMirror service.

Are you planning of continuing the module? It really works great and has a lot of potential.

Can’t help with programming but could in researching, testing, etc.

Thanks

**Comment by gauravsacc** [comment]
Yes, I do plan to continue the module. I should have time in the holiday season ;)

**Comment by varadwattamwar** [comment]
@gauravsacc 
My sample code works fine. I changed my subscribe key and public key in assistant.py also I entered magic-mirror-device-id and after running assistant.py I receive msgs: pubnub subscription completed and hello from python!! but there is no response from google assistant , google assistant does not work.
PLease help me out. Thanks in advance.
